### ISSUE TITLE
slow dl speed

### ISSUE THREAD

**Issue by isoldmysoull** [Chr1st-oo/pydeezer#2]
hey, thanks for your work, but download is a little bit slow is that because the decryption on saving chunks? or it's my internet?

**Comment by acgonzales** [comment]
> because the decryption on saving chunks?

The program is decrypting only <= 2048 bytes of data so I don't think its the problem here.

I think the culprit is in your internet. I just tried it now and its giving me my regular download speed. Maybe something is limiting your bandwidth or your download speed. Another **very unlikely** problem here is a very slow storage disk (writing the data to disk).
